// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DetailsInfo: typeof import('./src/components/details/src/detailsInfo.vue')['default']
    Download: typeof import('./src/components/download/src/download.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/header.vue')['default']
    Image: typeof import('./src/components/player/src/Image.vue')['default']
    ImgVideo: typeof import('./src/components/player/src/imgVideo.vue')['default']
    Log: typeof import('./src/components/log/src/log.vue')['default']
    Player: typeof import('./src/components/player/src/Player.vue')['default']
    Ptz: typeof import('./src/components/stream/src/ptz.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    Splayer: typeof import('./src/components/player/src/Splayer.vue')['default']
    Stream: typeof import('./src/components/stream/src/stream.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
