export declare const pkg: any;
export declare const isDebug: boolean;
export declare const str2Obj: (str: string) => any;
export declare const sleep: (time: number) => Promise<unknown>;
export declare const createStateEndDatetime: (type: number, beforeHour: number) => any[];
export declare const randomString: (len: number, chars?: string) => string;
export declare const getQueryVariable: (key: string) => string;
export declare const toggleFullScreen: (elem: HTMLElement | any, fullScreen?: boolean) => void;
export declare const number2hex: (dec: number, len: number) => string;
type Collection<T> = (a: Array<T>, b: Array<T>) => Array<T>;
export declare const intersect: (array1: [], array2: []) => never[];
export declare const minus: Collection<number>;
export declare const complement: (array1: [], array2: []) => void;
export declare const onKeyDown: (e: KeyboardEvent) => void;
export {};
