/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Download: typeof import('./src/components/download/src/download.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    Header: typeof import('./src/components/header.vue')['default']
    HtmlPlayer: typeof import('./src/components/player/src/htmlPlayer.vue')['default']
    Image: typeof import('./src/components/player/src/Image.vue')['default']
    ImgVideo: typeof import('./src/components/imgvideo/src/imgVideo.vue')['default']
    LabelProcess: typeof import('./src/components/labelprocess/src/labelProcess.vue')['default']
    Log: typeof import('./src/components/log/src/log.vue')['default']
    ProcessDataView: typeof import('./src/components/process/src/processDataView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTree: typeof import('./src/components/process/src/selectTree.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    StaticSidebar: typeof import('./src/components/staticSidebar.vue')['default']
    TablesPageFm: typeof import('./src/components/tables/src/tablesPageFm.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
    Tree: typeof import('./src/components/process/src/tree.vue')['default']
  }
}
