/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Download: typeof import('./src/components/download/src/download.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/header.vue')['default']
    HtmlPlayer: typeof import('./src/components/player/src/htmlPlayer.vue')['default']
    Image: typeof import('./src/components/player/src/Image.vue')['default']
    ImgVideo: typeof import('./src/components/imgvideo/src/imgVideo.vue')['default']
    LabelProcess: typeof import('./src/components/labelprocess/src/labelProcess.vue')['default']
    Log: typeof import('./src/components/log/src/log.vue')['default']
    ProcessDataView: typeof import('./src/components/process/src/processDataView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTree: typeof import('./src/components/process/src/selectTree.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    StaticSidebar: typeof import('./src/components/staticSidebar.vue')['default']
    TablesPageFm: typeof import('./src/components/tables/src/tablesPageFm.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
    Tree: typeof import('./src/components/process/src/tree.vue')['default']
  }
}
